-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 22:11:48 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema assistanceLogger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assistanceLogger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assistanceLogger` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `assistanceLogger` ;

-- -----------------------------------------------------
-- Table `assistanceLogger`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistanceLogger`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL COMMENT 'Hashed with SHA1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistanceLogger`.`assistant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistanceLogger`.`assistant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assistant_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_assistant_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `assistanceLogger`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistanceLogger`.`medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistanceLogger`.`medicine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `isActive` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistanceLogger`.`medicineDose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistanceLogger`.`medicineDose` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medicine_id` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `dose` VARCHAR(10) NULL,
  `preferredTime` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medicineDose_medicine1_idx` (`medicine_id` ASC),
  CONSTRAINT `fk_medicineDose_medicine1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `assistanceLogger`.`medicine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistanceLogger`.`medicineUsageLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistanceLogger`.`medicineUsageLog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medicineDose_id` INT NOT NULL,
  `assistant_id` INT NOT NULL,
  `medicineGiven` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medicineUsageLog_medicineDose1_idx` (`medicineDose_id` ASC),
  INDEX `fk_medicineUsageLog_assistant1_idx` (`assistant_id` ASC),
  CONSTRAINT `fk_medicineUsageLog_medicineDose1`
    FOREIGN KEY (`medicineDose_id`)
    REFERENCES `assistanceLogger`.`medicineDose` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicineUsageLog_assistant1`
    FOREIGN KEY (`assistant_id`)
    REFERENCES `assistanceLogger`.`assistant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
